run:
     timeout: 5m
     go: "1.26.0"

linters-settings:
    govet:
        enable:
            - shadow
    revive:
        rules:
            - name: exported
            - name: var-naming
            - name: package-comments
    gocritic:
        enable-tags:
            - diagnostic
            - style
            - perfomance
    errcheck:
        check-type-assertions: true
        ckeck-blank: true

linters:
    disable-all: true
    enable:
        - errcheck
        - govet
        - ineffasign
        - staticcheck
        - unused
        - gocritic
        - bodyclose
        - sqlclosecheck

issues:
    eclude-rules:
        - path: _test\.go
          linters:
            - revive
            - errcheck
        
output:
    formats:
        - format: colored-line-number
    print-issued-lines: true
    print-linter-name: true
              