name: "Feature Request"
description: "Suggest a new feature or improvement for p-manager"
title: "[FEAT]: "
labels: ["enhancement"]
assignees:
  - stepan41k

body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does the feature solve?
      description: "A clear description of the inconvenience or problem."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Description of the proposed solution
      description: How do you think the new feature should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Have you considered other ways of solving this problem?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information, terminal interface mockups, or examples from other utilities.